domain_path: C:\FPGA\UART_FIR\UART_FIR\VITIS\platform\export\platform\sw\standalone_microblaze_riscv_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
lang: c
