# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGA/UART_FIR/UART_FIR/UART_FIR.srcs/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2.xci
# IP: The module: 'sub_system_microblaze_riscv_0_axi_intc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/FPGA/UART_FIR/UART_FIR/UART_FIR.srcs/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2.xci
# IP: The module: 'sub_system_microblaze_riscv_0_axi_intc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_microblaze_riscv_0_axi_intc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
