# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/FPGA/UART/UART.srcs/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3.xci
# IP: The module: 'sub_system_mdm_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/UART/UART.gen/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_mdm_1_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART/UART.gen/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_mdm_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/FPGA/UART/UART.srcs/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3.xci
# IP: The module: 'sub_system_mdm_1_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGA/UART/UART.gen/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_mdm_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/FPGA/UART/UART.gen/sources_1/bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3_ooc_trace.xdc
# XDC: The top module name and the constraint reference have the same name: 'sub_system_mdm_1_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
