# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/UART_FIR/Nexys-Video-Master.xdc

# Block Designs: bd/sub_system/sub_system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system || ORIG_REF_NAME==sub_system} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_microblaze_riscv_0_0/sub_system_microblaze_riscv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_microblaze_riscv_0_0 || ORIG_REF_NAME==sub_system_microblaze_riscv_0_0} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_dlmb_v10_3/sub_system_dlmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_dlmb_v10_3 || ORIG_REF_NAME==sub_system_dlmb_v10_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_ilmb_v10_3/sub_system_ilmb_v10_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_ilmb_v10_3 || ORIG_REF_NAME==sub_system_ilmb_v10_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_dlmb_bram_if_cntlr_3/sub_system_dlmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_dlmb_bram_if_cntlr_3 || ORIG_REF_NAME==sub_system_dlmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_ilmb_bram_if_cntlr_3/sub_system_ilmb_bram_if_cntlr_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_ilmb_bram_if_cntlr_3 || ORIG_REF_NAME==sub_system_ilmb_bram_if_cntlr_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_lmb_bram_3/sub_system_lmb_bram_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_lmb_bram_3 || ORIG_REF_NAME==sub_system_lmb_bram_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_periph_imp_xbar_3/sub_system_microblaze_riscv_0_axi_periph_imp_xbar_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_microblaze_riscv_0_axi_periph_imp_xbar_3 || ORIG_REF_NAME==sub_system_microblaze_riscv_0_axi_periph_imp_xbar_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_periph_3/sub_system_microblaze_riscv_0_axi_periph_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_microblaze_riscv_0_axi_periph_3 || ORIG_REF_NAME==sub_system_microblaze_riscv_0_axi_periph_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_microblaze_riscv_0_axi_intc_2/sub_system_microblaze_riscv_0_axi_intc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_microblaze_riscv_0_axi_intc_2 || ORIG_REF_NAME==sub_system_microblaze_riscv_0_axi_intc_2} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_microblaze_riscv_0_xlconcat_2/sub_system_microblaze_riscv_0_xlconcat_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_microblaze_riscv_0_xlconcat_2 || ORIG_REF_NAME==sub_system_microblaze_riscv_0_xlconcat_2} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_mdm_1_3/sub_system_mdm_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_mdm_1_3 || ORIG_REF_NAME==sub_system_mdm_1_3} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_clk_wiz_1_4/sub_system_clk_wiz_1_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_clk_wiz_1_4 || ORIG_REF_NAME==sub_system_clk_wiz_1_4} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_rst_clk_wiz_1_100M_4/sub_system_rst_clk_wiz_1_100M_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_rst_clk_wiz_1_100M_4 || ORIG_REF_NAME==sub_system_rst_clk_wiz_1_100M_4} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_axi_uartlite_0_1/sub_system_axi_uartlite_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_axi_uartlite_0_1 || ORIG_REF_NAME==sub_system_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_axi_bram_ctrl_0_0/sub_system_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_axi_bram_ctrl_0_0 || ORIG_REF_NAME==sub_system_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_axi_bram_ctrl_0_bram_1/sub_system_axi_bram_ctrl_0_bram_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_axi_bram_ctrl_0_bram_1 || ORIG_REF_NAME==sub_system_axi_bram_ctrl_0_bram_1} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_axi_gpio_0_0/sub_system_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_axi_gpio_0_0 || ORIG_REF_NAME==sub_system_axi_gpio_0_0} -quiet] -quiet

# IP: bd/sub_system/ip/sub_system_axi_gpio_1_0/sub_system_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sub_system_axi_gpio_1_0 || ORIG_REF_NAME==sub_system_axi_gpio_1_0} -quiet] -quiet

# XDC: c:/FPGA/UART_FIR/UART_FIR/UART_FIR.gen/sources_1/bd/sub_system/sub_system_ooc.xdc
